### ISSUE TITLE
Unable to migrate

### ISSUE THREAD

**Issue by kehuili** [api7/kong-to-apisix#35]
Hi, I was trying to use kong-to-apisix to migrate Kong to APISIX, and I followed detail guide.

At first I got some pattern errors in log, so I just deleted consumers to make it work.
![20211101-160359](https://user-images.githubusercontent.com/35578392/139640704-ef8882bb-b57e-4d1d-9dae-b30089d88007.png)

However, this time it still didn't work. I did got some warns but there were no errors in log. 
![image](https://user-images.githubusercontent.com/35578392/139641745-5c3032c7-274e-4faf-86cc-51a802e4d718.png)

I would like to know if there are some ways to debug. Thank you.

**Comment by shuaijinchao** [comment]
Please provide the declarative configuration of Kong in text form.

**Comment by shuaijinchao** [comment]
The current log information is only the log of the prompt level. Switching to ETCD as the configuration center will have the same output. Have you performed functional tests?

**Comment by kehuili** [comment]
> Please provide the declarative configuration of Kong in text form.

```
_format_version: "1.1"
consumers:
- basicauth_credentials:
  - password: 6b559c842e6540b152e8b6f49b4f9af13a5f0216
    username: test
  username: test
services:
- connect_timeout: 60000
  host: console-httpbin-latest.compass-ha.svc.cluster.local
  name: test-cert-httpbin
  path: /headers
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: test-cert-httpbin
    path_handling: v0
    paths:
    - /cert-test/headers
    plugins:
    - enabled: true
      name: cert-auth
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
  write_timeout: 60000
```

**Comment by kehuili** [comment]
> The current log information is only the log of the prompt level. Switching to ETCD as the configuration center will have the same output. Have you performed functional tests?

Not yet. Can you provide an instruction on how to do it?

**Comment by shuaijinchao** [comment]
What do you mean by the operating instructions? How to use kong-to-apisix? Or how to apply the converted configuration to APISIX?

**Comment by kehuili** [comment]
> What do you mean by the operating instructions? How to use kong-to-apisix? Or how to apply the converted configuration to APISIX?

I mean functional tests you mentioned above.

**Comment by shuaijinchao** [comment]
Verify through the client that the access and response of kong and apisix are consistent and in line with expectations.

**Comment by kehuili** [comment]
> Verify through the client that the access and response of kong and apisix are consistent and in line with expectations.

Oh my bad. I tried to make a request and it did work. However APISIX dashboard is empty, that's why I thought migration failed. Then my question becomes that after migration, why dashboard is still empty.

**Comment by kehuili** [comment]
By the way after migration, Kong and APISIX didn't act same way. I need to request different urls to get same result.
Kong: /cert-test/headers
APISIX:  /cert-test/headers/headers

Here's my configurations in Kong:
* Service
![image](https://user-images.githubusercontent.com/35578392/140040385-4a2db287-940b-4b97-95c2-706951dff68d.png)
* Route
![image](https://user-images.githubusercontent.com/35578392/140040413-05805c1c-fd70-410b-aa1c-e2bd0e537d51.png)

**Comment by shuaijinchao** [comment]
> > Verify through the client that the access and response of kong and apisix are consistent and in line with expectations.
> 
> Oh my bad. I tried to make a request and it did work. However APISIX dashboard is empty, that's why I thought migration failed. Then my question becomes that after migration, why dashboard is still empty.

The APISIX data plane and the control plane are decoupled, and only the data added through the control plane can be seen in the Dashboard.

**Comment by shuaijinchao** [comment]
> By the way after migration, Kong and APISIX didn't act same way. I need to request different urls to get same result. Kong: /cert-test/headers APISIX: /cert-test/headers/headers
> 
> Here's my configurations in Kong:
> 
> * Service
>   ![image](https://user-images.githubusercontent.com/35578392/140040385-4a2db287-940b-4b97-95c2-706951dff68d.png)
> * Route
>   ![image](https://user-images.githubusercontent.com/35578392/140040413-05805c1c-fd70-410b-aa1c-e2bd0e537d51.png)

What is the response to APISIX request `/cert-test/headers`?

**Comment by kehuili** [comment]
> What is the response to APISIX request `/cert-test/headers`?

APISIX response with this home page
![image](https://user-images.githubusercontent.com/35578392/140246995-1f5ccb80-bf22-4fb2-99c1-13a85e37ad6c.png)

while Kong response
![image](https://user-images.githubusercontent.com/35578392/140247030-dc10cf2a-bc1a-487e-aa65-47d04718eb9d.png)

**Comment by shuaijinchao** [comment]
Please send the complete configuration of kong and apisix yaml

**Comment by kehuili** [comment]
APISIX:
```
services:
- id: 8da1d894-fd80-457c-880a-c51384801bab
  name: test-cert-httpbin
  upstream_id: cdc9a57c-6a6c-4fce-8b5d-d94e6bd08bfb
routes:
- id: "1"
  name: test-cert-httpbin
  uri: /cert-test/headers*
  plugins:
    proxy-rewrite:
      regex_uri:
      - ^/cert-test/headers/?(.*)
      - /$1
  service_id: 8da1d894-fd80-457c-880a-c51384801bab
upstreams:
- id: cdc9a57c-6a6c-4fce-8b5d-d94e6bd08bfb
  type: roundrobin
  nodes:
  - host: console-httpbin-latest.compass-ha.svc.cluster.local
    port: 80
    weight: 100
  retries: 5
  timeout:
    connect: 60
    send: 60
    read: 60
  scheme: http
consumers:
- username: test
  plugins:
    basic-auth:
      username: test
      password: 6b559c842e6540b152e8b6f49b4f9af13a5f0216
#END
```

Kong:
```
_format_version: "1.1"
consumers:
- basicauth_credentials:
  - password: 6b559c842e6540b152e8b6f49b4f9af13a5f0216
    username: test
  username: test
services:
- connect_timeout: 60000
  host: console-httpbin-latest.compass-ha.svc.cluster.local
  name: test-cert-httpbin
  path: /headers
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: test-cert-httpbin
    path_handling: v0
    paths:
    - /cert-test/headers
    plugins:
    - enabled: true
      name: cert-auth
      protocols:
      - grpc
      - grpcs
      - http
      - https
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
  write_timeout: 60000
```

**Comment by shuaijinchao** [comment]
This is the result I exported.


---

```yaml
services:
- id: 46f2bd79-8886-4d91-b6b4-f5f3e6432581
  name: test-cert-httpbin
  upstream_id: 8de86f6d-f83c-424b-bf71-901da3b70dc2
routes:
- id: 3c813bd3-48c5-4a64-ae2b-145dbe4505a4
  name: test-cert-httpbin
  uri: /cert-test/headers*
  plugins:
    proxy-rewrite:
      regex_uri:
      - ^/cert-test/headers/?(.*)
      - /headers/$1
  service_id: 46f2bd79-8886-4d91-b6b4-f5f3e6432581
upstreams:
- id: 8de86f6d-f83c-424b-bf71-901da3b70dc2
  type: roundrobin
  nodes:
  - host: console-httpbin-latest.compass-ha.svc.cluster.local
    port: 80
    weight: 100
  retries: 5
  timeout:
    connect: 60
    send: 60
    read: 60
  scheme: http
consumers:
- username: test
  plugins:
    basic-auth:
      username: test
      password: 6b559c842e6540b152e8b6f49b4f9af13a5f0216
#END
```
